### ISSUE TITLE
Can not override default styles - CSS class multiplication

### ISSUE THREAD

**Issue by tbydza** [janosh/svelte-multiselect#140]
Hello, 
I want to use this component, but I have problem overriding default styles. After some dubbuging and reading [this discussion about style preprocessing](https://github.com/janosh/svelte-multiselect/issues/117) I've found that prefix css class generated by svelte for style scoping gets multiplied in resulting css (from `:where(div.multiselect)` to this `.svelte-19kmkoq.svelte-19kmkoq.svelte-19kmkoq.svelte-19kmkoq:where(div.multiselect)`. Due to the high specificity of this selector it is hard to override it with my custom class.

I am not sure, but I think it has to do with scss preprocessing. Can you fix this or provide some workaround?

currently generated CSS:
```css
.svelte-19kmkoq.svelte-19kmkoq.svelte-19kmkoq.svelte-19kmkoq:where(div.multiselect) {
    position: relative;
    align-items: center;
    display: flex;
    cursor: text;
    border: var(--sms-border, 1pt solid lightgray);
    border-radius: var(--sms-border-radius, 3pt);
    background: var(--sms-bg);
    max-width: var(--sms-max-width);
    padding: var(--sms-padding, 0 3pt);
    color: var(--sms-text-color);
    font-size: var(--sms-font-size, inherit);
    min-height: var(--sms-min-height, 19pt);
    margin: var(--sms-margin);
}
```

CSS generated in v6:
```css
.svelte-18t61g:where(div.multiselect) {
    position: relative;
    align-items: center;
    display: flex;
    cursor: text;
    border: var(--sms-border, 1pt solid lightgray);
    border-radius: var(--sms-border-radius, 3pt);
    background: var(--sms-bg);
    max-width: var(--sms-max-width);
    padding: var(--sms-padding, 0 3pt);
    color: var(--sms-text-color);
    font-size: var(--sms-font-size, inherit);
    min-height: var(--sms-min-height, 19pt);
    margin: var(--sms-margin);
}
```
